export const ADMIN_ROUTE = '/admin/:direction?'
export const SHOP_ROUTE = '/category/:brand?/:type?'
export const MAIN_ROUTE = '/'
export const DEVICE_ROUTE = '/device/:id'
export const ALL_CATEGORY = '/all_category/'